data_dict = {
    "round_num":"**int** round", 
    "tick":"**int** time unit (128 ticks per second)", 
    "side":"**str** T (terrorist) or CT (counterterrorist) that team is playing",
    "team":"**str** team",
    "hp":"**str** current health points",
    "armor":"**int** current armor value",
    "is_alive":"**boolean** if player is alive or dead",
    "x":"**int** x coordinate",
    "y":"**int** y coordinate",
    "z":"**int** z coordinate",
    "inventory":"**dict/json** what the player is carrying and equipment details",
    "total_utility":"**int** number of utility (grenades, flashes, smokes, inced) in inventory",
    "equipment_value_freezetime_end":"**int** value of equipment after purchase time ends",
    "area_name":"**str** location that the player is",
    "seconds":"**int** elapsed time (resets to zero after bomb plant)",
    "clock_time":"**str** in-game clock timer (resets to 0:40 after bomb plant)",
    "t_alive":"**int** number of T alive",
    "ct_alive":"**int** number of CT alive",
    "bomb_planted":"**boolean** if the bomb has been planted yet",
    "map_name":"**str** map being played",
    "utility_used":"**int** number of utility use",
    "player":"**str** player name"
}

type_dict = {
    "round_num":int,
    "tick":int, 
    "side":str,
    "team":str,
    "hp":str,
    "armor":int,
    "is_alive":bool,
    "x":int,
    "y":int,
    "z":int,
    "inventory":dict,
    "total_utility":int,
    "equipment_value_freezetime_end":int,
    "area_name":str,
    "seconds":int,
    "clock_time":str,
    "t_alive":int,
    "ct_alive":int,
    "bomb_planted":bool,
    "map_name":str,
    "utility_used":int,
    "player":str
}